name: lightsensor_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - anaconda
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - shap
  - shapely
  - astropy
  - pytz